name: Pull Request Checks

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Linting (flake8)
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Use Python version 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install Flake8
      run: |
        python -m pip install flake8
    - name: Run linting tests
      run: | 
        flake8 src/model/
  tests:
    name: Unit tests (pytest)
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - name: Check out repo
      uses: actions/checkout@v4
    - name: Use Python version 3.8
      uses: actions/setup-python@v5
      with:
        python-version: "3.8"
    - name: Install Pytest
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install -r requirements.txt
    - name: Ensure PYTHONPATH
      run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
    - name: Run pytest
      run: |
        pytest tests/